### ISSUE TITLE
请问这个库与lua-resty-http的区别是什么

### ISSUE THREAD

**Issue by liuyangc3** [timebug/lua-resty-httpipe#6]

**Comment by timebug** [comment]
这个库目前在我们公司的平台上（UPYUN）使用，因为我们自身业务涉及到比较多需要在 HTTP 请求以及解析响应的过程中进行一些 Hack，这个库能够提供更加精细的控制粒度，使得我们业务代码更加直观。

所以，总结而言，目前主要是设计接口风格上的差异，后续我们会持续在功能特性上初步丰富起来。
