### ISSUE TITLE
随着程序运行时间的增长，cpu负载不断增高

### ISSUE THREAD

**Issue by fc13240** [timebug/lua-resty-httpipe#7]
您好，

我目前有这样一个需求，cdn访问lua，lua从外部连接获取并解析修改数据后返回，我用yum 装的openresty，用ngx.location.capture、resty.http和您这个插件，程序运行2小时左右，四个work的CPU都会升到50%左右，随着时间的推移，CPU到100%，请问这大概是什么原因？我还有一个程序是访问内部链接（127.0.0.1）没有这个问题。
我的并发200左右，并且一直保持这个数，CPU负载上升应该和并发没关系。

**Comment by timebug** [comment]
> 我目前有这样一个需求，cdn访问lua，lua从外部连接获取并解析修改数据后返回，我用yum 装的openresty，用ngx.location.capture、resty.http和您这个插件，程序运行2小时左右，四个work的CPU都会升到50%左右，随着时间的推移，CPU到100%，请问这大概是什么原因？

您方便提供下一些对分析有帮助的代码片段吗？这个库我们在生产环境使用好久了，库本身并不会导致 CPU 持续增高问题。

**Comment by fc13240** [comment]
谢谢，已经解决了。

在 2017年8月30日 上午10:08，Monkey Zhang <notifications@github.com>写道：
